modLoader="javafml"
loaderVersion="[32,)"
license="All rights reserved"

[[mods]]
modId="travel_anchors"
version="${file.jarVersion}"
displayName="Travel Anchors"
credits="MelanX and noeppi_noeppi"
authors="CastCrafter"
description='''
Adds a staff of travelling and a travel anchor to teleport around the world.
'''

[[dependencies.travel_anchors]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.travel_anchors]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
